### ISSUE TITLE
[Feature Request] Bot Support

### ISSUE THREAD

**Issue by kwadroke** [Lewisk3/MechDoomer#6]
I'd love to play this with Mech VS Mech Bot support. I've seen video of it bit not sure how you got it going.

Do I need another WAD file to add bots? Not looking to add Doom enemies but other Mechs.

**Comment by Lewisk3** [comment]
Mechs can currently be spawned in via some `summon` commands. 
`summon mais_####` replace `####` with the name of the mech you want to spawn.

**Comment by kwadroke** [comment]
The command seems to be case sensitive. I had to run `summon MAIS_MadDog` in-order to get get an AI to spawn.

**Comment by Lewisk3** [comment]
It should function fine regardless of case, actually.
Might be different with the Linux version of GZDoom, I don't see why it would be though.

**Comment by kwadroke** [comment]
For some reason it wouldn't spawn anything before without it being case sensitive.... Now it's working. Must be a PEBKAC problem.
