### ISSUE TITLE
[Suggestion] Better or quicker way to scrap stuff. 

### ISSUE THREAD

**Issue by Elkinda** [Lewisk3/MechDoomer#7]
Takes me a while to scrap stuff in the mech lab (I like to try and save up for a new mech mid-playthrough). What about something like a "Scrap All" button? Or a hotkey you can press while having something selected?

If this is already a thing, I apologize. **Love** this mod.

**Comment by Lewisk3** [comment]
I'm looking into implementing a hotkey atm, however It may just not be possible.
GZDoom's menu system is honestly incredibly poorly implemented and it's very difficult to do even basic things like, 
detect a bound key being pressed. 

I'll update this if/when I figure it out.

**Comment by Lewisk3** [comment]
Implemented Scrap Hotkey and Scrap All. (Hold Shift while pressing the Scrap button)
