### ISSUE TITLE
[Crash] Exiting a level at high velocity

### ISSUE THREAD

**Issue by Elkinda** [Lewisk3/MechDoomer#8]
GZDOOM 4.5.0

I have crashed a few times after a level. After some experimentation I have found it only seems to happen when moving and fast.

Recreate:

Load up DOOM2 map01 with a fast mech (I used commando)

reach exit with preferably no monsters

get some speed and exit the level with high KPH

it should crash with this message

![gzdoom_DaFu3iVE8b](https://user-images.githubusercontent.com/40741635/110221048-dbef8100-7e97-11eb-973a-b45f847f7c4c.png)

**Comment by Lewisk3** [comment]
Bug is fixed, will be pushed with the next update.
