### ISSUE TITLE
[Bug] Couple of potential bugs I found

### ISSUE THREAD

**Issue by Elkinda** [Lewisk3/MechDoomer#9]
AMS/LAMS shooting at own lasers (mwd_laserbeams = true). This only happens when hitting monsters with a laser (mwd_laserbeams = true) while having a AMS/LAMS equipped.

Enemy Mechs that replace the Cyberdemons pick up items for you when they walk over it.

You seem to be able to stack on armor past your set limit (medium armor component pickup).

You can manually repair yourself with the medium armor components without powering down (Intentional?)

**Comment by Lewisk3** [comment]
> Enemy Mechs that replace the Cyberdemons pick up items for you when they walk over it.

Lol, I'll look into fixing this, Enemy mechs are essentially voodoos of the existing player, so it makes sense why this would occur.

> You seem to be able to stack on armor past your set limit (medium armor component pickup).

This is actually intended behavior, and will allow you to go over your rated armor spec, provided you have the tonnage to do so.
Over Armor of course will not be repaired and losing it is permanent. 

> You can manually repair yourself with the medium armor components without powering down (Intentional?)

Kind of an oversight, although I'm not sure I'll be changing this behavior, I will if it leads to being a little too OP. 

> AMS/LAMS shooting at own lasers (mwd_laserbeams = false). This only happens when hitting monsters with a laser (mwd_laserbeams = false) while having a AMS/LAMS equipped.

I cannot seem to reproduce this bug, oddly enough. Not sure what could be causing it for you.

**Comment by Elkinda** [comment]
> > AMS/LAMS shooting at own lasers (mwd_laserbeams = false). This only happens when hitting monsters with a laser (mwd_laserbeams = false) while having a AMS/LAMS equipped.
> 
> I cannot seem to reproduce this bug, oddly enough. Not sure what could be causing it for you.

Did I say false? I meant mwd_laserbeams = true.
Try it with that

**Comment by Lewisk3** [comment]
> > > AMS/LAMS shooting at own lasers (mwd_laserbeams = false). This only happens when hitting monsters with a laser (mwd_laserbeams = false) while having a AMS/LAMS equipped.
> > 
> > 
> > I cannot seem to reproduce this bug, oddly enough. Not sure what could be causing it for you.
> 
> Did I say false? I meant mwd_laserbeams = true.
> Try it with that

Ah, I was able to reproduce it under those conditions and it has been fixed.
Will be pushed whenever I can figure out how to solve the AI picking up items bug.
